"""The rule-based "What stood out" panel.

Every flag is produced by an explicit, inspectable rule with a threshold from
config.yaml. Nothing here is generated by a language model: the panel has to be
reproducible and auditable, and a reader must be able to ask "why did that
appear?" and get an exact answer.

Each rule is a small pure function returning ``Flag | None``, so a rule can be
unit-tested in isolation and added without touching the others.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

Severity = Literal["high", "notable", "info"]

#: Ordering used when more flags fire than the panel has room for.
_SEVERITY_RANK: dict[Severity, int] = {"high": 0, "notable": 1, "info": 2}


@dataclass(frozen=True, slots=True)
class Flag:
    """One notable condition.

    Attributes:
        category: Rule family, e.g. ``"move"`` or ``"curve"``. Drives the icon.
        text: The sentence shown to the reader.
        severity: Used to rank flags when the panel overflows.
        value: The magnitude that triggered it, used as a tie-breaker.
        key: The instrument or series it concerns.
    """

    category: str
    text: str
    severity: Severity = "notable"
    value: float | None = None
    key: str | None = None


#: U+2212. Used everywhere numbers are rendered so columns align and the
#: flag text matches the tables.
MINUS = "\u2212"


def _sign(value: float) -> str:
    """Explicit +/− prefix, so colour is never the only signal."""
    return f"+{value:.2f}" if value >= 0 else f"{MINUS}{abs(value):.2f}"


def flag_return_zscore(
    key: str, label: str, zscore: float | None, return_pct: float | None, threshold: float
) -> Flag | None:
    """Flag a daily move that is large relative to the asset's own history."""
    if zscore is None or abs(zscore) < threshold:
        return None

    direction = "rose" if (return_pct or 0) >= 0 else "fell"
    move = f" {_sign(return_pct)}%" if return_pct is not None else ""
    return Flag(
        category="move",
        text=f"{label} {direction}{move}, a {abs(zscore):.1f}σ move versus its past year.",
        severity="high" if abs(zscore) >= threshold + 1 else "notable",
        value=abs(zscore),
        key=key,
    )


def flag_extreme(key: str, label: str, extreme: str | None, window_label: str) -> Flag | None:
    """Flag a new trailing high or low."""
    if extreme is None:
        return None
    return Flag(
        category="extreme",
        text=f"{label} closed at a new {window_label} {extreme}.",
        severity="notable",
        key=key,
    )


def flag_ma_cross(key: str, label: str, window: int, cross: str | None) -> Flag | None:
    """Flag a moving-average cross."""
    if cross is None:
        return None
    direction = "above" if cross == "above" else "below"
    return Flag(
        category="trend",
        text=f"{label} crossed {direction} its {window}-day moving average.",
        severity="notable",
        key=key,
    )


def flag_vix_term_structure(ratio: float | None, threshold: float) -> Flag | None:
    """Flag VIX term structure moving into backwardation.

    Backwardation — near-term implied volatility above three-month — signals
    that the market is pricing stress now rather than later. It is unusual
    enough to be worth surfacing whenever it happens.
    """
    if ratio is None or ratio < threshold:
        return None
    return Flag(
        category="volatility",
        text=(
            f"VIX term structure is in backwardation (VIX/VIX3M {ratio:.2f}), "
            "with near-term implied volatility above three-month."
        ),
        severity="high",
        value=ratio,
        key="^VIX",
    )


def flag_curve_transition(name: str, transition: str | None, spread_bp: float) -> Flag | None:
    """Flag a curve spread inverting or un-inverting."""
    if transition is None:
        return None
    return Flag(
        category="curve",
        text=f"The {name} spread has {transition} and stands at {spread_bp:+.0f}bp.",
        severity="high",
        value=abs(spread_bp),
        key=name,
    )


def flag_credit_move(
    key: str, label: str, change_bp: float | None, threshold_bp: float
) -> Flag | None:
    """Flag an unusually large one-day credit spread move."""
    if change_bp is None or abs(change_bp) < threshold_bp:
        return None
    direction = "widened" if change_bp > 0 else "tightened"
    return Flag(
        category="credit",
        text=f"{label} {direction} {abs(change_bp):.0f}bp on the day.",
        severity="high" if abs(change_bp) >= threshold_bp * 2 else "notable",
        value=abs(change_bp),
        key=key,
    )


def rank_flags(flags: list[Flag], max_flags: int) -> list[Flag]:
    """Order flags by severity then magnitude, and trim to the panel size.

    Args:
        flags: Every flag that fired, in any order.
        max_flags: Maximum to display.

    Returns:
        The most significant flags. A quiet day legitimately produces none.
    """
    ordered = sorted(
        flags,
        key=lambda f: (_SEVERITY_RANK[f.severity], -(f.value or 0.0)),
    )
    return ordered[:max_flags]
